Extension { #name : #UITheme }

{ #category : #'*Mirage-Highlighter' }
UITheme >> mirageHighlighterBorderColor [
	^ Color fromString: '#3297d4'
]

{ #category : #'*Mirage-Highlighter' }
UITheme >> mirageHighlighterBorderWidth [
	^ 3
]

{ #category : #'*Mirage-Highlighter' }
UITheme >> mirageTaskbarTasksHighlighterColor [
	^ Color fromString: '#3297d4'
]

{ #category : #'*Mirage-Highlighter' }
UITheme >> mirageTaskbarTasksHighlighterHeight [
	^ 5
]
