Extension { #name : #UITheme }

{ #category : #'*Mirage-Carousel' }
UITheme >> mirageCarouselColor [
	^ Color transparent
]

{ #category : #'*Mirage-Carousel' }
UITheme >> mirageSpaceBetweenThumbnails [
	^ 10
]

{ #category : #'*Mirage-Carousel' }
UITheme >> mirageThumbnailsBorderColor [
	^ Color gray
]

{ #category : #'*Mirage-Carousel' }
UITheme >> mirageThumbnailsBorderWidth [
	^ 3
]

{ #category : #'*Mirage-Carousel' }
UITheme >> mirageThumbnailsSelectedBorderColor [
	^ Color fromString: '#3297d4'
]
