initialization
initialize
	super initialize.
	self
		color: Smalltalk ui theme mirageCarouselColor;
		thumbnailsBorderColor: Smalltalk ui theme mirageThumbnailsBorderColor;
		thumbnailsSelectedBorderColor: Smalltalk ui theme mirageThumbnailsSelectedBorderColor;
		thumbnailsBorderWidth: Smalltalk ui theme mirageThumbnailsBorderWidth;
		spaceBetweenThumbnails: Smalltalk ui theme mirageSpaceBetweenThumbnails